version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 7200:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress_web
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 123456
    command: --init-file /init/init.sql
    ports:
        - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/init/init.sql

volumes:
  wordpress:
  db: